// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrfrrpgewetndgnxqmso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndyZnJycGdld2V0bmRnbnhxbXNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNTU1ODksImV4cCI6MjA2NTczMTU4OX0.5TtLPWt1qZBnV7xBc2x2GRhzwpVXnKRRU2dbFh0aS94";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);